### ISSUE TITLE
problem proteta

### ISSUE THREAD

**Issue by diemort** [GASP-UFRGS/LHE-Proton-Writer#16]
![histos_10kevt_proteta FULL_inner final madgraph log](https://github.com/GASP-UFRGS/LHE-Proton-Writer/assets/5755070/986d3cba-1fc2-4e43-b125-82027167cfe5)

**Comment by Artur-UF** [comment]
I suspect the problem is that there is no proton (ID = 2212) in neither of the 3 samples, the most recent PR fixed it by only generating plots containing particles identified by IDS in the root_input
